[project]
name = "python-toolbox"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "pydantic[email]>=2.13.4",
]

[dependency-groups]
dev = [
    "rust-just>=1.58.0",
]
lint = [
    "mypy>=2.3,<2.4",
    "pre-commit>=4.6.1",
    "ruff>=0.16.1",
    "types-jsonschema>=4.26.0.20260518",
]
test = [
    "jsonschema>=4.26.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "pytest-randomly>=4.1.0",
]

[tool.uv]
default-groups = "all"
preview-features = ["audit-command"]

[tool.ruff]
cache-dir = ".cache/ruff"

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "I", # isort
    "PGH", # pygrep-hooks
    "UP", # pyupgrade
    "S", # flake8-bandit
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "DJ", # flake8-django
    "DTZ", # flake8-datetimez
    "G", # flake8-logging-format
    "PT", # flake8-pytest-style
    "T20", # flake8-print
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "FURB", # refurb
    "RUF", # Ruff-specific rules
]
ignore = [
    # Conflict with the formatter.
    "W191", # tab-indentation
    "E111", # indentation-with-invalid-multiple
    "E114", # indentation-with-invalid-multiple-comment
    "E117", # over-indented
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101", # assert
    "S105", # hardcoded-password-string
]

[tool.mypy]
strict = true
cache_dir = ".cache/mypy"
mypy_path = "utilities"

[tool.pytest]
strict = true
cache_dir = ".cache/pytest"
pythonpath = ["utilities"]
testpaths = ["tests", "utilities"]
addopts = [
    "--doctest-modules",
    "--import-mode", "importlib",
    "--cov-config", "pyproject.toml",
    "--cov-report", "term:skip-covered",
    "--cov-report", "html",
    "--cov-fail-under", "100",
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
    "only: shorthand mark used to select a small subset of test cases for debugging",
]

[tool.coverage.run]
branch = true
data_file = ".cache/coverage/data.db"
disable_warnings = ["no-data-collected"]
omit = [
    "utilities/graceful.py",
]

[tool.coverage.report]
exclude_also = [
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\\bProtocol\\):",
    "@overload",
]

[tool.coverage.html]
directory = "var/cov-report"

[tool.markdownlint]
default = true
MD007 = { indent = 4 }
MD013 = { line_length = 88, strict = true }
